"""Initial migration for Room and Equipment models

Revision ID: 577e3bfb952c
Revises: 
Create Date: 2024-11-19 15:31:38.759353

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "577e3bfb952c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_room_capacity"), ["capacity"], unique=False
        )

    op.create_table(
        "equipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["room.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("equipment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_equipment_room_id"), ["room_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_equipment_room_id"))

    op.drop_table("equipment")
    with op.batch_alter_table("room", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_room_capacity"))

    op.drop_table("room")
    # ### end Alembic commands ###
