"""Add indexes for reservations

Revision ID: 59787a8735f7
Revises: 9e0f22160721
Create Date: 2024-12-02 21:07:15.904063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59787a8735f7'
down_revision = '9e0f22160721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_cancel_date'), ['cancel_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_room_date_range', ['room_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_user_date_range', ['user_id', 'start_date', 'end_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_user_date_range')
        batch_op.drop_index('ix_room_date_range')
        batch_op.drop_index(batch_op.f('ix_reservations_user_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_start_date'))
        batch_op.drop_index(batch_op.f('ix_reservations_room_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_end_date'))
        batch_op.drop_index(batch_op.f('ix_reservations_cancel_date'))

    # ### end Alembic commands ###
