version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-reservation-service
    ports:
      - "5010:5010"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "FLASK_APP=app.run:create_app flask db upgrade &&
             gunicorn -w 4 -b 0.0.0.0:5010 app.run:app --chdir /app"
    networks:
      - app-network

networks:
  app-network:
    external: true 
