version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-reservation-service
    ports:
      - "5010:5010"
    volumes:
      - ./app:/app  
      - ./app/config:/app/config 
      - ./migrations:/app/migrations
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: sh -c "flask db upgrade && flask run --host=0.0.0.0 --port=5010"
    networks:
      - app-network

networks:
  app-network:
    external: true 
