version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-room-service
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: >
      sh -c "FLASK_APP=app.run:create_app flask db upgrade &&
             gunicorn -w 4 -b 0.0.0.0:5005 app.run:app --chdir /app"
    networks:
      - app-network

networks:
  app-network:
    external: true

