version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3050:3050"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - app-network

networks:
  app-network:
    external: true
      