version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-container
    ports:
      - "3050:3050"
    environment:
      NODE_ENV: production
      PORT: 3050
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm start"
    restart: always
