"""Added index to email column

Revision ID: 99e53914f4de
Revises: 5ac7f3006842
Create Date: 2024-11-19 10:55:02.984404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e53914f4de'
down_revision = '5ac7f3006842'
branch_labels = None
depends_on = None


def upgrade():
    # Sprawdzamy, czy baza danych to PostgreSQL czy SQLite
    if op.get_bind().dialect.name == 'postgresql':
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_constraint('users_email_key', type_='unique')
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
    elif op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint('users_email_key', ['email'])

    # ### end Alembic commands ###
